import Head from 'next/head';
import { About, Hero, Layout, Product } from '@/components';
import { useRef } from 'react';

export default function Home() {
  const aboutRef = useRef(null);
  const productRef = useRef(null);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Layout
        aboutRef={aboutRef}
        productRef={productRef}>
        <Hero />
        <About aboutRef={aboutRef} />
        <Product productRef={productRef} />
      </Layout>
    </>
  );
}
