import Head from 'next/head';
import { About, Hero, Layout, Product } from '@/components';
import { useRef } from 'react';
import useData from '@/hooks/useData';

export default function Home() {
  const aboutRef = useRef(null);
  const productRef = useRef(null);
  const { data, isLoading } = useData('api/v1/ads');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Layout
        aboutRef={aboutRef}
        productRef={productRef}
        dataHeader={data?.hero}
        dataFooter={data?.hero}>
        <Hero
          data={data?.hero}
          isLoading={isLoading}
        />
        <About
          aboutRef={aboutRef}
          data={data?.about}
          isLoading={isLoading}
        />
        <Product
          productRef={productRef}
          data={data?.product}
          isLoading={isLoading}
        />
      </Layout>
    </>
  );
}
