import Head from 'next/head';
import { About, Hero, Layout, Product, Gambling } from '@/components';
import { useRef, useState, useEffect } from 'react';

export default function Home() {
  const aboutRef = useRef(null);
  const productRef = useRef(null);
  const [windowWidth, setWindoWidth] = useState(null);
  const [isGambling, setIsGambling] = useState(false);
  useEffect(() => {
    const handleWindowResize = () => {
      setWindoWidth(window.innerWidth);
    };
    window.addEventListener('resize', handleWindowResize);

    return () => {
      window.removeEventListener('resize', handleWindowResize);
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      {windowWidth < 576 ? (
        isGambling ? (
          <Gambling />
        ) : (
          <Layout
            aboutRef={aboutRef}
            productRef={productRef}>
            <Hero />
            <About aboutRef={aboutRef} />
            <Product productRef={productRef} />
          </Layout>
        )
      ) : (
        <Layout
          aboutRef={aboutRef}
          productRef={productRef}>
          <Hero />
          <About aboutRef={aboutRef} />
          <Product productRef={productRef} />
        </Layout>
      )}
    </>
  );
}
